services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "uvicorn calendar_planner.asgi:application --reload --host 0.0.0.0 --port 8000 --log-level debug"
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      calendar_db:
        condition: service_healthy
    networks:
      - calendar-network

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "uvicorn calendar_planner.asgi:application --reload --host 0.0.0.0 --port 8001 --log-level debug"
    expose:
      - "8001"
    env_file:
      - .env
    depends_on:
      calendar_db:
        condition: service_healthy
    networks:
      - calendar-network
  
  calendar_db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - calendar-network

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    networks:
      - calendar-network
  
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A calendar_planner beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - calendar-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A calendar_planner worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - calendar-network

  kanchi:
    image: getkanchi/kanchi
    container_name: kanchi_calendar
    ports:
      - "3000:3000"
      - "8765:8765"
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PWD}@calendar_db:${POSTGRES_PORT}/${POSTGRES_DB}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    volumes:
      - kanchi-data:/data
    restart: unless-stopped
    depends_on:
      - redis
      - celery_worker
    networks:
      - calendar-network

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A calendar_planner flower --port=5555
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
    ports:
      - '5555:5555'
    networks:
      - calendar-network

  minio:
    image: minio/minio
    container_name: calendar_minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_KEY}
    volumes:
      - ./data:/data
    command: server /data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/code/static
    depends_on:
      - web
    networks:
      - calendar-network
    
  openssl:
    image: alpine/openssl
    volumes:
      - ./certs:/certs
    command: >
      req -x509 -nodes -newkey rsa:4096 -keyout /certs/cert.key
      -out /certs/cert.crt -days 365
      -subj "/C=UA/ST=Kharkiv/L=Kharkiv/O=Hillel1/OU=Lecture/CN=localhost"

volumes:
  kanchi-data:

networks:
  calendar-network:
    driver: bridge